### ISSUE TITLE
Dataset availability

### ISSUE THREAD

**Issue by eawer** [levguy/talksumm#1]
Hello! In your paper, it is told that the dataset and the related code are available publicly, but as for now, the repo is empty. Can you please tell if it is possible to get the dataset and/or look through the code?

**Comment by williamwonglongone** [comment]
Looking forward to your open datasets

**Comment by williamwonglongone** [comment]
Looking forward to your open content.

**Comment by levguy** [comment]
Hi, the dataset and code are released. Thank you for your interest!
