### ISSUE TITLE
Not all the papers in test set have video resources, how to compare the results with SciSummNet?

### ISSUE THREAD

**Issue by JaniceXiong** [levguy/talksumm#2]
I think the test set is https://github.com/WING-NUS/scisumm-corpus/tree/master/data/Test-Set-2018
But I retreive these papers in test set and find that not all the papers have video resources.
So if the video data is unavailable, how to use the HMM method described in TalkSumm paper and get the comparable results?

**Comment by levguy** [comment]
Hi, thanks for your interest.
The HMM method was used to create a weakly-labeled dataset (the TalkSumm dataset). We then trained a neural model on this dataset, and evaluated this model on the CL-SciSumm test set.
